services:
  server:
    build: ./server
    image: weight-monitor-server:0.1.2
    ports:
      - "4000:4000"
    volumes:
      - ./server/data:/usr/src/app/data
    restart: unless-stopped

  client:
    build: ./client
    image: weight-monitor-client:0.1.2
    ports:
      - "5000:80"
    depends_on:
      - server
    restart: unless-stopped
